repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace

  # - repo: https://github.com/adrienverge/yamllint
  #   rev: v1.35.1
  #   hooks:
  #     - id: yamllint

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
       # Run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --ignore, S104]
      # Run the formatter
      - id: ruff-format
