repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: local
    hooks:
      - id: python-unit-tests
        name: panama unit tests
        entry: pytest -k tests
        pass_filenames: false
        types: [python]
        language: system


  - repo: https://github.com/psf/black
    rev: "24.8.0"
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --ignore, S104]
      - id: ruff-format
