services:
  prefect:
    image: prefecthq/prefect:3-python3.10
    container_name: prefect
    ports:
      - "4200:4200"
    command: prefect server start --host 0.0.0.0 --port 4200
    environment:
      - PREFECT_API_SERVICES_FLOW_RUN_NOTIFICATIONS_ENABLED=false
  kiebids_ocr:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    depends_on:
      - prefect
    container_name: kiebids_ocr
    ports:
      - "5151:5151"
      - "5152:5152"
    volumes:
      - ../data:/app/data
      - ../models/sam_vit_b_01ec64.pth:/app/models/sam_vit_b_01ec64.pth
      - ../models/craft_mlt_25k.pth:/root/.EasyOCR/model/craft_mlt_25k.pth
      - ../models/latin_g2.pth:/root/.EasyOCR/model/latin_g2.pth
    environment:
      - PREFECT_API_URL=http://host.docker.internal:4200/api
      - PYTHONPATH=/app
    # command: python kiebids/ocr_flow.py
    command: python kiebids/ocr_flow.py --serve-deployment