mode: debug
log_level: DEBUG

shared_folder: /mnt/data/ZUG-Biodiversität

image_path: data/images
max_images: 2
output_path: data/output
debug_path: data/debug

fiftyone_dataset: "mfn-dataset"
fiftyone_database_dir: data/debug/fifty-db

evaluation: data/evaluation

evaluation_paths:
  hymdata: /mnt/data/ZUG-Biodiversität/data/hymdata_sample/20230511T160908__coll.mfn-berlin.de_u_78a081 # yamllint disable-line
