# Workflow config

# Path to input /images directory
image_path: /mnt/data/ZUG-Biodiversität/data/labels_fossinv_insekten_20200723/images # yamllint disable-line

# Path to output directories
output_path: data/output

# Evaluation settings
evaluation: False
evaluation_path: data/evaluation
xml_path: /mnt/data/ZUG-Biodiversität/data/labels_fossinv_insekten_20200723/page_xml # yamllint disable-line

# Debug configs
mode: debug
debug_path: data/debug
max_images: 5  # number of images to process, useful for debugging

log_level: DEBUG

fiftyone_dataset: "mfn-dataset"
fiftyone_database_dir: data/debug/fifty-db
disable_fiftyone: false
