# Workflow config

# Path to input /images directory
image_path: /mnt/data/ZUG-Biodiversität/data/labels_fossinv_insekten_20200723/images # yamllint disable-line
max_images: 5  # number of images to process

# Path to output directories
output_path: data/output

# Evaluation settings
run_tag: # Specify a name to identify the run (optional)
evaluation: false
evaluation_path: data/evaluation
xml_path: /mnt/data/ZUG-Biodiversität/data/labels_fossinv_insekten_20200723/page_xml # yamllint disable-line

# Debug configs
mode: debug
debug_path: data/debug

log_level: DEBUG

fiftyone_dataset: "mfn-dataset"
fiftyone_database_dir: data/debug/fifty-db
disable_fiftyone: false

# Information on who created the XML file. Used in the XML output.
creator_info: |
  Information about the creator of the XML file.
