mode: debug
log_level: DEBUG

shared_folder: /mnt/data/ZUG-Biodiversität

image_path: data/images
max_images: 3
output_path: data/output
debug_path: data/debug

fiftyone_dataset: "mfn-dataset"
fiftyone_database_dir: /app/fifty-db

evaluation: data/evaluation

# Datasets for evaluation
evaluation_datasets:
  labels_fossinv_insekten_20200723:
    image_path: /mnt/data/ZUG-Biodiversität/data/labels_fossinv_insekten_20200723/images # yamllint disable-line
    xml_path: /mnt/data/ZUG-Biodiversität/data/labels_fossinv_insekten_20200723/page_xml # yamllint disable-line
  readcoop_drawer_78a081:
    image_path: /mnt/data/ZUG-Biodiversität/data/readcoop_drawer_78a081/images # yamllint disable-line
    xml_path: /mnt/data/ZUG-Biodiversität/data/readcoop_drawer_78a081/page_xml # yamllint disable-line
  readcoop_random_sample_20240903:
    image_path: /mnt/data/ZUG-Biodiversität/data/readcoop_random_sample_20240903/images # yamllint disable-line
    xml_path: /mnt/data/ZUG-Biodiversität/data/readcoop_random_sample_20240903/page_xml # yamllint disable-line
