pipeline_name: "KIEBIDS pipeline"
deployment_name: "KIEBIDS deployment"

preprocessing:
  gray: false
  smooth: false
  threshold: false
  denoise: false
  contrast: false
  # defines the maximum image dimension for the input images.
  # applied either to height or width max HD as default
  max_image_dimension: 1920

layout_analysis:
  name: "sam_vit_b_01ec64.pth"
  model_path: "models/sam_vit_b_01ec64.pth"
  model_type: "vit_b"
  points_per_side: 32
  pred_iou_thresh: 0.86
  stability_score_thresh: 0.92
  crop_n_layers: 0
  min_mask_region_area: 100
  output_mode: "binary_mask"  # "uncompressed_rle
  closing_kernel: 20

text_recognition:  # easyocr module
  model: "moondream" # Options: 'easyocr', 'moondream'
  easyocr:
    language: "de"
    text_threshold: 0.7  # Text confidence threshold
    decoder: "greedy"  # Options: 'greedy', 'beamsearch', 'wordbeamsearch'
    paragraph: false
    y_ths: 0.3 # Vertical distance for text grouping
  moondream:
    name: "vikhyatk/moondream2"
    revision: "2025-01-09"
    trust_remote_code: true
    prompt: |
      Transcribe all printed and handwritten text on this label of a specimen
      from a collection of a museum for natural history, being especially
      careful to preserve any scientific names, dates, and location information.
      Maintain the original formatting and line breaks. Most text is in German.

semantic_labeling:

entity_linking:
  geonames_api_url: "http://api.geonames.org/searchJSON"