# Workflow config

# Path to input /images directory
image_path: data/images

# Path to output directories
output_path: data/output

# Evaluation settings
run_tag: # Specify a tag to identify the run (optional)
evaluation: false
evaluation_path: data/evaluation
xml_path: ""

# Debug configs
mode:  # debug
debug_path: data/debug
max_images: 5  # number of images to process, useful for debugging

log_level: INFO  # DEBUG

fiftyone_dataset: "mfn-dataset"
fiftyone_database_dir: data/debug/fifty-db
disable_fiftyone: true
