# Workflow config

# Path to input /images directory
image_path: data/images

# Path to output directories
output_path: data/output
eval_path: data/evaluation

# Path to evaluation data
evaluation_dataset:
  image_path: ""
  xml_path: ""

# Debug configs
mode:  # debug
debug_path: data/debug
max_images: 5  # number of images to process, useful for debugging

log_level: INFO  # DEBUG

fiftyone_dataset: "mfn-dataset"
fiftyone_database_dir: data/debug/fifty-db
disable_fiftyone: true
