# Workflow config

# Path to input /images directory
image_path: data/images
max_images: 50  # number of images to process

# Path to output directories
output_path: data/output

# Evaluation settings
run_id: # Specify a name to identify the run
evaluation: false
evaluation_path: data/evaluation
xml_path: "data/page_xml"

# Debug configs
mode:  # debug
debug_path: data/debug

log_level: INFO  # DEBUG

fiftyone_dataset: "mfn-dataset"
fiftyone_database_dir: data/debug/fifty-db
disable_fiftyone: true
