# Workflow config

# Path to input /images directory
image_path: /mnt/data/ZUG-Biodiversität/data/labels_fossinv_insekten_20200723/images # yamllint disable-line
# image_path: data/input

# Path to output directories
output_path: data/output
evaluation_path: data/evaluation
evaluation: True

# Path to evaluation data
evaluation_dataset:
  image_path: /mnt/data/ZUG-Biodiversität/data/labels_fossinv_insekten_20200723/images # yamllint disable-line
  xml_path: /mnt/data/ZUG-Biodiversität/data/labels_fossinv_insekten_20200723/page_xml # yamllint disable-line


# Debug configs
mode:  # debug
debug_path: data/debug
max_images: 5  # number of images to process, useful for debugging

log_level: INFO  # DEBUG

fiftyone_dataset: "mfn-dataset"
fiftyone_database_dir: data/debug/fifty-db
