name: Quality

on:
  push:
    branches:
      - '**'

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Fetch only the latest commit
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.13'
          cache: 'pip'
      - run: pip install ruff==0.7.2

      - name: Run Ruff Format
        run: ruff format . --check

      - name: Run Ruff Lint
        run: ruff check .
