name: Tests

on:
  workflow_dispatch:  # allows manual trigger from GitHub UI
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Fetch only the latest commit
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.13'
          cache: 'pip'  # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -vv tests/*.py
        env:
          PYTHONPATH: ${{ github.workspace }}  # add project root directory
